### ISSUE TITLE
Throwing Error while trying to migrate snapshots created by DLM policies 

### ISSUE THREAD

**Issue by santoshkatageri** [thenickdude/snap-to-s3#8]
I am trying to migrate the snapshots created by a DLM policy to s3 bucket.

The snapshot is tagged with aws:snapshots etc

`[snap-0b0xxxxxxxb] An error occurred, tagging snapshot with "migrate" so it can be retried later
[snap-0b0cxxxxxxxxx] { Error: snap-0bxxxxxxxxxxxb: Error: S3 upload failed: InvalidTag: Your TagKey cannot be prefixed with aws:
    at SnapshotMigrationError (/usr/lib/node_modules/snap-to-s3/lib/snap-to-s3.js:1948:3)
    at _raceToMarkSnapshot.then.then (/usr/lib/node_modules/snap-to-s3/lib/snap-to-s3.js:1682:12)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  error: 
   Error: S3 upload failed: InvalidTag: Your TagKey cannot be prefixed with aws:
       at uploader.promise.then.e (/usr/lib/node_modules/snap-to-s3/lib/snap-to-s3.js:426:14)
       at process._tickDomainCallback (internal/process/next_tick.js:135:7),
  snapshotID: 'snap-0b0xxxxxxxxxx' }

Terminating due to fatal errors.
`

**Comment by thenickdude** [comment]
Thanks for the report, this should be fixed now via 0d44ddddd6214c4b565f047906b871fb470ec40e !

**Comment by santoshkatageri** [comment]
Hey @thenickdude,  That's was a very fast response. and that's solved my issue.
